dist: bionic
language: generic

stages:
  - test
  - name: dev_build
    if: (branch = master) AND (type = push)
  - name: stable_build
    if: (tag IS present) AND (tag =~ ^v) AND (type = push)

env:
  global:
    - DOCKER_IMAGE_NAME: bestdoctor/its_on
    - DEV_IMAGE: $DOCKER_IMAGE_NAME:dev-$TRAVIS_COMMIT  
    - LATEST_DEV_IMAGE: $DOCKER_IMAGE_NAME:latest-dev
    - STABLE_IMAGE: $DOCKER_IMAGE_NAME:$TRAVIS_TAG
    - LATEST_IMAGE: $DOCKER_IMAGE_NAME:latest

jobs:
  include:
    - stage: test
      language: python
      python:
        - "3.8"
      env:
        - HADOLINT: "${HOME}/hadolint"
        - DYNACONF_DATABASE__dsn: "postgresql://postgres@localhost:5432/tests"
        - DYNACONF_DATABASE__superuser_dsn: "postgresql://postgres@localhost:5432/postgres"
      addons:
        postgresql: "12"
        apt:
          packages:
            - postgresql-12
      services:
        - postgresql
        - redis
      install:
        - gem install mdl
        - curl -sL -o ${HADOLINT} "https://github.com/hadolint/hadolint/releases/download/v1.17.6/hadolint-$(uname -s)-$(uname -m)"
        - chmod 700 ${HADOLINT}
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - pip install -r requirements.txt
      before_script:
        - ./cc-test-reporter before-build
      script:
        - mdl README.md
        - git ls-files --exclude='Dockerfile*' --ignored | xargs --max-lines=1 ${HADOLINT}
        - make check
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

    - stage: dev_build
      services:
        - docker
      before_script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
      script:
        - docker build -t $DEV_IMAGE -t $LATEST_DEV_IMAGE .
        - docker push $DEV_IMAGE
        - docker push $LATEST_DEV_IMAGE

    - stage: stable_build
      services:
        - docker
      before_script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
      script:
        - docker build -t $STABLE_IMAGE -t $LATEST_IMAGE .
        - docker push $STABLE_IMAGE
        - docker push $LATEST_IMAGE
