version: '3'
services:
  cache:
    image: redis
    container_name: its-on-redis

  db:
    image: postgres
    container_name: its-on-postgres
    environment:
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_USER: itson
      POSTGRES_DB: itson

  web:
    image: bestdoctor/its_on:local
    build: .
    container_name: its-on
    environment:
      HOST: '0.0.0.0'
      DATABASE_DSN: postgresql://itson:strongpassword@db:5432/itson
      REDIS_URL: redis://cache:6379/0
      CACHE_URL: redis://cache:6379/1
    ports:
     - "127.0.0.1:8081:8081"
    depends_on:
      - cache
      - db
