[pytest]
asyncio_mode = auto
filterwarnings =
    ignore:distutils Version classes are deprecated:DeprecationWarning
    ignore:The '__version__' attribute is deprecated:DeprecationWarning
    ignore:'crypt' is deprecated:DeprecationWarning
    ignore:The 'missing' attribute of fields is deprecated:marshmallow.warnings.RemovedInMarshmallow4Warning
    ignore:body argument is deprecated for http web exceptions:DeprecationWarning
    ignore:Deprecated API features detected:sqlalchemy.exc.RemovedIn20Warning
