"""Add m2m relation to manage user switches

Revision ID: 20ce9b327cdb
Revises: 4f13ecf8ddfd
Create Date: 2019-10-25 14:28:27.366591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20ce9b327cdb'
down_revision = '4f13ecf8ddfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_switches',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('switch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['switch_id'], ['switches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.UniqueConstraint('switch_id', 'user_id', name='user_switch_unique')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_switches')
    # ### end Alembic commands ###
