"""Added ttl and jira_ticket fields to switch model

Revision ID: 58df78852dc7
Revises: b85b82664c28
Create Date: 2021-09-20 17:32:34.154705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58df78852dc7'
down_revision = 'b85b82664c28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('switches', sa.Column('jira_ticket', sa.String(length=255), nullable=True))
    op.add_column('switches', sa.Column('ttl', sa.Integer(), nullable=False, default=60))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('switches', 'ttl')
    op.drop_column('switches', 'jira_ticket')
    # ### end Alembic commands ###
