"""empty message

Revision ID: 63454ba6d6f9
Revises: 1510fb99ed70
Create Date: 2019-09-18 19:50:30.830643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63454ba6d6f9'
down_revision = '1510fb99ed70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('switches', sa.Column('version', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('switches', 'version')
    # ### end Alembic commands ###
