"""Remove jira_ticket field

Revision ID: 91cc2dd4ae43
Revises: 58df78852dc7
Create Date: 2021-10-04 16:31:07.196148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91cc2dd4ae43'
down_revision = '58df78852dc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('switches', 'jira_ticket')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('switches', sa.Column('jira_ticket', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
