"""add created_at and updated_at

Revision ID: 94ccd671cbcd
Revises: 7fb20e27a402
Create Date: 2021-03-15 17:52:27.373967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94ccd671cbcd'
down_revision = '7fb20e27a402'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('switches', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('switches', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('switches', 'updated_at')
    op.drop_column('switches', 'created_at')
    # ### end Alembic commands ###
