"""Added switch history

Revision ID: b85b82664c28
Revises: 94ccd671cbcd
Create Date: 2021-03-26 15:56:26.634107

"""
from alembic import op
import sqlalchemy as sa

from its_on.utils import AwareDateTime

# revision identifiers, used by Alembic.
revision = 'b85b82664c28'
down_revision = '94ccd671cbcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('switch_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('switch_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('new_value', sa.String(length=64), nullable=False),
    sa.Column('changed_at', AwareDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['switch_id'], ['switches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('switch_history')
    # ### end Alembic commands ###
