"""empty message

Revision ID: cb42b1c187d9
Revises: 63454ba6d6f9
Create Date: 2019-09-23 18:08:45.570743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb42b1c187d9'
down_revision = '63454ba6d6f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_group_is_active', 'switches', ['group', 'is_active'], unique=False)
    op.create_index('idx_group_version_is_active', 'switches', ['group', 'version', 'is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_group_version_is_active', table_name='switches')
    op.drop_index('idx_group_is_active', table_name='switches')
    # ### end Alembic commands ###
