"""add deleted_at

Revision ID: f3cd679c723f
Revises: 49e21e1bb766
Create Date: 2022-10-27 16:10:28.151400

"""
import sqlalchemy as sa
from alembic import op

from its_on.utils import AwareDateTime

# revision identifiers, used by Alembic.
revision = 'f3cd679c723f'
down_revision = '49e21e1bb766'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('switches', sa.Column('deleted_at', AwareDateTime(), nullable=True))
    op.execute(f"UPDATE switches SET deleted_at=now() where is_hidden=True")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('switches', 'deleted_at')
    # ### end Alembic commands ###
