"""empty message

Revision ID: f5a2fe518eae
Revises: cb42b1c187d9
Create Date: 2019-09-24 11:33:14.636156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5a2fe518eae'
down_revision = 'cb42b1c187d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_name_group_is_active', 'switches', ['name', 'group', 'is_active'], unique=False)
    op.create_index('idx_name_group_version_is_active', 'switches', ['name', 'group', 'version', 'is_active'], unique=False)
    op.drop_index('idx_group_is_active', table_name='switches')
    op.drop_index('idx_group_version_is_active', table_name='switches')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_group_version_is_active', 'switches', ['group', 'version', 'is_active'], unique=False)
    op.create_index('idx_group_is_active', 'switches', ['group', 'is_active'], unique=False)
    op.drop_index('idx_name_group_version_is_active', table_name='switches')
    op.drop_index('idx_name_group_is_active', table_name='switches')
    # ### end Alembic commands ###
