from its_on.config import settings

SVG_BADGE_SETTINGS = settings.FLAG_SVG_BADGE

SVG_BADGE_BACKGROUND_COLOR = SVG_BADGE_SETTINGS.BACKGROUND_COLOR

SWITCH_IS_ACTIVE_SVG_BADGE_PREFIX = SVG_BADGE_SETTINGS.PREFIX.IS_ACTIVE
SWITCH_IS_INACTIVE_SVG_BADGE_PREFIX = SVG_BADGE_SETTINGS.PREFIX.IS_INACTIVE
SWITCH_IS_HIDDEN_SVG_BADGE_PREFIX = SVG_BADGE_SETTINGS.PREFIX.IS_HIDDEN
SWITCH_NOT_FOUND_SVG_BADGE_PREFIX = SVG_BADGE_SETTINGS.PREFIX.NOT_FOUND

# Slug: строчные латинские буквы и цифры, слова разделены одиночным дефисом
ENVIRONMENT_NAME_PATTERN = r'^[a-z0-9]+(-[a-z0-9]+)*$'
