from its_on.settings import settings

svg_badge_settings = settings.flag_svg_badge

SVG_BADGE_BACKGROUND_COLOR = svg_badge_settings.background_color

SWITCH_IS_ACTIVE_SVG_BADGE_PREFIX = svg_badge_settings.prefix.is_active
SWITCH_IS_INACTIVE_SVG_BADGE_PREFIX = svg_badge_settings.prefix.is_inactive
SWITCH_IS_HIDDEN_SVG_BADGE_PREFIX = svg_badge_settings.prefix.is_hidden
SWITCH_NOT_FOUND_SVG_BADGE_PREFIX = svg_badge_settings.prefix.not_found
